### ISSUE TITLE
ReadConfiguration() function in loop section

### ISSUE THREAD

**Issue by Abdelalihub** [bneedhamia/sdconfigfile#9]
is it possible to read the configuration in the file each time ?
i plan to change the configuration in the file while the execution of the code !
i tried that , but the function reads the variables for 5 times and after that it reads nothing , in the serial.print() it shows variables blank !
thanks

**Comment by bneedhamia** [comment]
Please call cfg.end() followed by cfg.begin() before you try to read the configuration file again.

Let me know whether that change fixes the problem. If it doesn't please reply with an example of your code that isn't working and I'll take a look at it.

Thanks,
Brad
